import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../shared/models/invoice_model.dart';

class PdfHelper {
  static Future<Uint8List> generateInvoicePdf(
    InvoiceModel invoice, {
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: pageFormat,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        invoice.companyName,
                        style: pw.TextStyle(
                          fontSize: 20,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.Text('Official Sales Receipt & Tax Invoice'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        'INV #: ${invoice.invoiceNumber}',
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),
                      pw.Text('Date: ${invoice.date.toString().substring(0, 10)}'),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 10),

              // Customer info
              pw.Text('Billed To: ${invoice.customerName}',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              if (invoice.tableNo != null) pw.Text('Table: ${invoice.tableNo}'),
              pw.SizedBox(height: 15),

              // Items Table
              pw.TableHelper.fromTextArray(
                headers: ['Item Description', 'Qty', 'Unit Price', 'Subtotal'],
                data: invoice.items.map((item) {
                  return [
                    item.name,
                    '${item.quantity}',
                    '${invoice.currency}${item.unitPrice.toStringAsFixed(2)}',
                    '${invoice.currency}${item.subtotal.toStringAsFixed(2)}',
                  ];
                }).toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
                cellAlignment: pw.Alignment.centerLeft,
              ),

              pw.SizedBox(height: 15),
              pw.Divider(),

              // Totals
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                          'Subtotal: ${invoice.currency}${invoice.rawSubtotal.toStringAsFixed(2)}'),
                      if (invoice.discountPercentage > 0)
                        pw.Text(
                            'Discount (${invoice.discountPercentage.toStringAsFixed(0)}%): -${invoice.currency}${invoice.discountAmount.toStringAsFixed(2)}'),
                      if (invoice.taxPercentage > 0)
                        pw.Text(
                            'Tax (${invoice.taxPercentage.toStringAsFixed(0)}%): +${invoice.currency}${invoice.taxAmount.toStringAsFixed(2)}'),
                      pw.SizedBox(height: 5),
                      pw.Text(
                        'Grand Total: ${invoice.currency}${invoice.grandTotal.toStringAsFixed(2)}',
                        style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ],
              ),

              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text(
                  'Generated by SUNMI Hardware Test Suite',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }
}
